### ISSUE TITLE
No file when posting to .Net Web API?

### ISSUE THREAD

**Issue by PaulAik** [Mischi/angularjs-imageupload-directive#5]
Hi,

I'm having some trouble posting files to a .Net Web API site. It appears the file is being added to the form and posted, but when it arrives at the server the code can't find any files attached to the form (there's a property on the http request called "files" that I'm checking).

Is there any additional configuration I might need on the Angular side so my server picks up the files within the form?

I tried out another Angular JS file upload solution and it appears to work fine - but I like the additional features this project has (resizing etc).

Thanks,

Paul

**Comment by Mischi** [comment]
Hi,

i have an example  [ImageUploadController](https://github.com/Mischi/ContactManager-Demo/blob/master/ContactManager.Web/api/UploadImageController.cs) with a slightly modified [MultipartFormDataStreamProvider ](https://github.com/Mischi/ContactManager-Demo/blob/master/ContactManager.Web/Infrastructure/UniqueMultipartFormDataStreamProvider.cs)

I think the Files property can't handle [Multipart Forms](http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) 

Regards,

Fabian

**Comment by PaulAik** [comment]
MS not conforming to standards? Figures.

Thanks very much for the example - I'll check it out.
